apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-nightly-results
  namespace: guidellm-nightly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
